modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0"

[[mods]]
modId="somnia_awoken_reforged"
version="${file.jarVersion}"
displayName="Somnia Awoken Reforged"
logoFile="logo.png"
authors="Somnia Awoken, Dreamdawn"
description="Overhauls vanilla sleep mechanics: accelerated world simulation, fatigue system, custom wake-up time, and sleep fade transitions."

[[dependencies.somnia_awoken_reforged]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.somnia_awoken_reforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.somnia_awoken_reforged]]
    modId="koremods"
    mandatory=true
    versionRange="[0.6,)"
    ordering="NONE"
    side="BOTH"